# Project info
site_name: AutoRadiomics
site_description: The easiest tool for experimenting with Radiomics features
site_author: Piotr Woznicki

docs_dir: docs

# Repository
repo_url: https://github.com/pwoznicki/AutoRadiomics
repo_name: pwoznicki/AutoRadiomics

# Configuration
theme:
  name: readthedocs

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight

# Plugins
plugins:
  - search
  - mkdocstrings

# Page tree
nav:
  - Home:
      - AutoRadiomics: index.md
  - Reference:
      - Data: autorad/data.md
      - Feature extraction: autorad/feature_extraction.md
      - Preprocessing: autorad/preprocessing.md
      - Feature selection: autorad/feature_selection.md
      - Models: autorad/models.md
      - Training: autorad/training.md
      - Evaluation: autorad/evaluation.md
      - Inference: autorad/inference.md
      - Visualizations: autorad/visualization.md
