name: Build web application

on:
  push:
    branches:
    - feature-desktop-app
  pull_request:
    branches:
    - feature-desktop-app
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu", "macos", "windows"]
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install numpy pyoxidizer
    - name: Install Node
      uses: actions/setup-node@v3
      with:
         node-version: "14"
    - name: make build app
      run: make build-app
    - uses: actions/upload-artifact@v3
      with:
        name: AutoRadiomicsApp-${{ runner.os }}
        path: |
          js/app/dist/*.dmg
          js/app/dist/*.exe
          js/app/dist/*.snap
          js/app/dist/*.AppImage
          !js/app/dist/*unpacked/
